import 'package:flutter/material.dart';

const USER_ID = "UserID";
const USERNAME = "UserName";
const LOGIN_ID = "LoginID";
const ROLE_ID = "RoleID";
const MOBILE = "Mobile";
const EMAIL = "Email";
const DEPT_ID = "DeptID";
const GATE_ID = "GateID";
const STATUS = "status";
const DATA = "Data";
const SUCCESS = "Success";
const FAILURE = "Failure";
const USER = "user";
const MESSAGE = "Message";
const QRSTATUSNAME = "QRSTATUSNAME";
const QRSTATUS = "QRSTATUS";
const MINERAL = "Mineral";
const ACTIVITY_ID = "ActivityID";
const DISTRICT_ID = "DistrictID";
const DESIGNATION = "Designation";
const SERVER_USER_NAME = "admin";
const SERVER_USER_PASSWORD = "I@CMS";
const SERVER_BASE_URL = "https://icms.digitalindiacorporation.in/I2CMS/index.php";
const SERVER_VERIFY_LOGIN = "$SERVER_BASE_URL?r=api/login";
const SERVER_OTP_GENERATE_VERIFY = "$SERVER_BASE_URL?r=api/otp";
const SERVER_ENCODING_TYPE = "multipart/form-data";
const SERVER_CHANGE_PASSWORD = "$SERVER_BASE_URL?r=api/changepassword";
const SERVER_SCAN_QR_CODE = "$SERVER_BASE_URL?r=api/scanqrcode";
const SERVER_GET_ISSUE = "$SERVER_BASE_URL?r=api/getissuetype";
const SERVER_REPORT_ISSUE = "$SERVER_BASE_URL?r=api/reportissue";
const SERVER_GET_MINERAL_TYPE ="$SERVER_BASE_URL?r=api/getmineraltype";
const SERVER_GET_REASONS = "$SERVER_BASE_URL?r=api/getreasons";
const SERVER_TRUCK_PASS = "$SERVER_BASE_URL?r=api/truckpass";
const SERVER_FILL_INFO = "$SERVER_BASE_URL?r=api/fillinfo";
const QRDETAILS = "QRDetails";

class QrDetails {
  static String WHO = "Who";
  static String WHEN = "When";
  static String QR_ID = "QrID";
  static String QR_CODE = "QrCode";
  static String UNIQUE_ID = "UniqueID";
  static String GENERATED_BY = "GeneratedBy";
  static String GENERATED_ON = "GeneratedOn";
  static String EXPIRY_DATE = "ExpiryDate";
  static String TYPE = "Type";
  static String WEIGHT = "Weight";
  static String GATE_ID = "GateID";
  static String BOOK_NO = "BookNo";
  static String SR_NO = "SrNo";
  static String DEPT_ID = "DeptId";
  static String REQUEST_ID = "RequestID";
  static String MINERAL_ID = "MineralID";
  static String MINERAL_NAME = "MineralName";
  static String WEIGHT_ID = "WeightID";
  static String GATE_NAME = "GateName";
  static String DEPT_NAME = "DeptName";
  static String PERMIT_NO = "PermitNo";
  static String PERMIT_DATE = "PermitDate";
  static String LEASE_ID = "LeaseID";
  static String LEASE_NAME = "LeaseName";
  static String LEASE_ADDRESS = "LeaseAddress";
}